### ISSUE TITLE
Multiple instances of the program running simultaneously causes an exception

### ISSUE THREAD

**Issue by jceddy** [jceddy/DailyArenaDeckAdvisor#118]
An unhandled exception was detected.

Exception:

System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Del-riqeo Brown\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor\database.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at DailyArena.Common.Core.Database.CardDatabase.UpdateCardDatabase()
   at DailyArena.Common.Core.Database.CardDatabase.Initialize(Boolean useProtectedData)
   at DailyArena.DeckAdvisor.MainWindow.<Window_Loaded>b__90_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\Del-riqeo Brown\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor\database.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at DailyArena.Common.Core.Database.CardDatabase.UpdateCardDatabase()
   at DailyArena.Common.Core.Database.CardDatabase.Initialize(Boolean useProtectedData)
   at DailyArena.DeckAdvisor.MainWindow.<Window_Loaded>b__90_0()
   at System.Threading.Tasks.Task.Execute()<---

[log2020010519_001.txt](https://clans.dailyarena.net/user_uploads/8b4e6cd9-1788-4f2d-88c2-51273c42eee9_log2020010519_001.txt)

[output_log.txt](https://clans.dailyarena.net/user_uploads/8b4e6cd9-1788-4f2d-88c2-51273c42eee9_output_log.txt)

**Comment by jceddy** [comment]
This appears to be an issue from multiple instances of the program running at the same time. Changing the title to match.
